#!/bin/bash

ceil() {                                                                       
  echo "define ceil (x) {if (x<0) {return x/1} \
        else {if (scale(x)==0) {return x} \
        else {return x/1 + 1 }}} ; ceil($1)" | bc
}

USR=`whoami`

FILE=$1
# TODO: validate input
CONF=./lp-dir/config/$(date +"%b-%Y").conf

DEBT=`grep $USR $CONF | awk 'BEGIN { ORS=" " }; {print $4}'`

if [ $DEBT -gt "0" ]; then
    echo "Cota insuficiente";
    exit 1;
fi

ARQ=`grep $USR $CONF | awk 'BEGIN { ORS=" " }; {print $3}'`

if [ $ARQ -eq "0" ]; then
   echo "Cota de arquivos insuficiente";
   exit 1;
fi

SIZE=`ls -l $FILE | awk 'BEGIN { ORS=" " }; {print $5}'`

FLOAT_PAG=`echo "scale=2; $SIZE / 3600" | bc`
PAG=`ceil $FLOAT_PAG`

AVAILABLE=`grep $USR $CONF | awk 'BEGIN { ORS=" " }; {print $2}'`

if [ "$PAG" -gt "$AVAILABLE" ]; then
    echo "Cota de paginas insuficiente";
    exit 1;
fi

# Comentei essa linha pq tava dando erro de impressora não definida
# Atualizar quando for submeter
# lp "$@"

if [ "$?" -eq "1" ]; then
    echo "Unable to print file";
    exit 1;
fi

NEWPAG=`grep $USR $CONF | awk -v PAG=$PAG 'BEGIN { ORS=" " }; {print $1, int($2)-int(PAG), int($3)-1, $4}'`

LINE=`grep -nr $USR $CONF | awk 'BEGIN {FS=":";OFS=":"}; {print $1}'`

sed -i "${LINE}s/.*/${NEWPAG}/" $CONF
