#!/bin/bash

. lp-dir/config/limits

DATE=`date -d "$2$101" +"%b-%Y"`
FILE=$DATE.conf
REPORT_FOLDER="./lp-dir/report"
REPORT_FOUND=`find $REPORT_FOLDER -name $FILE`

if [ -n "$REPORT_FOUND" ];
then
	IFS=$'\n'
	REPORT=`cat $REPORT_FOUND`
	for line in $REPORT; do
		echo "$line" | awk -v PAGE_LIMIT=$PAGE_LIMIT -v FILE_LIMIT=$FILE_LIMIT '{print $1, int(PAGE_LIMIT)-int($2)+int($4), int(FILE_LIMIT)-int($3)}'
	done;
else
	echo "No report available for date: $DATE"
fi
