#!/bin/bash

. lp-dir/config/limits

echo "page $PAGE_LIMIT"
echo "arq $FILE_LIMIT"

DATE=`date -d "$2$101" +"%b-%Y"`
FILE=$DATE.conf
REPORT_FOLDER="./lp-dir/report"
REPORT_FOUND=`find $REPORT_FOLDER -name $FILE`

if [ -n "$REPORT_FOUND" ];
then
	IFS=$'\n'
	REPORT=`cat $REPORT_FOUND`
	for i in $REPORT; do
		#for l in $i; do
		#	IFS=" "
		#	echo $l
		#done;
	done;
else
	echo "No report available for date: $DATE"
fi
